.TH "AES_res" 3 "Wed Sep 24 2014" "Crypto AES" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AES_res \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aes_all_modes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBtag\fP"
.br
.RI "\fIData tag, optional\&. \fP"
.ti -1c
.RI "int \fBtag_size\fP"
.br
.RI "\fIData tag size, in bytes\&. \fP"
.ti -1c
.RI "unsigned char * \fBoutput\fP"
.br
.RI "\fISecure data\&. \fP"
.ti -1c
.RI "int \fBoutput_size\fP"
.br
.RI "\fISecure data size, in bytes\&. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char* AES_res::output"

.PP
Secure data\&. 
.SS "int AES_res::output_size"

.PP
Secure data size, in bytes\&. 
.SS "unsigned char* AES_res::tag"

.PP
Data tag, optional\&. 
.SS "int AES_res::tag_size"

.PP
Data tag size, in bytes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Crypto AES from the source code\&.
